import { MaquininhaPorPlano } from "@/types/maquinas";

export const MaquinasYelly: MaquininhaPorPlano = {

    max: {
        Mini: {
            name: "Yelly Mini",
            desc: "A mais portátil!",
            imageUrl:
                "https://yelly.com.br/wp-content/uploads/2025/06/MINI-DESCONTO-MAX.png", 
            items: [
                "Frete Grátis",
                "+5% desconto  extra no PIX",
                "Link de Pagamento Grátis (Consulte condições)",
                "Comprovante por SMS",
                "Receba por aproximação (NFC)",
                "Aceite Pix com QR CODE",
                "Chip 3g Grátis + Wi-Fi",
                "Tela Touch screen",
                "Sistema Android",
                "Gestão de produtos/estoque (Confira disponibilidade)",
            ],
            oldPrice: 337.0,
            newPrice: 197.00,
            installmentPrice: 16.42,
            discount: 41,
            button: "Pedir Yelly Mini",
        },
        Pro: {
            name: "Yelly Pro",
            desc: "O melhor custo-benefício!",
            imageUrl:
                "https://yelly.com.br/wp-content/uploads/2025/06/PRO-DESCONTO-MAX.png",
            items: [
                "Frete Grátis",
                "+5% desconto  extra no PIX",
                "Link de Pagamento Grátis (Consulte condições)",
                "Comprovante impresso ou por SMS",
                "Receba por aproximação (NFC)",
                "Aceite Pix com QR CODE",
                "Chip 4G Grátis + Wi-Fi",
                "Tela Touch screen",
                "Sistema Android",
                "Gestão de produtos/estoque (Confira disponibilidade)",
            ],
            oldPrice: 497.0,
            newPrice: 297.0,
            installmentPrice: 24.75,
            discount: 40,
            button: "Pedir Yelly Pro",
        },
        Smart: {
            name: "Yelly Smart",
            desc: "A mais moderna!",
            imageUrl:
                "https://yelly.com.br/wp-content/uploads/2025/06/SMART-DESCONTO-MAX-1.png",
            items: [
                "Frete Grátis",
                "+5% desconto  extra no PIX",
                "Link de Pagamento Grátis (Consulte condições)",
                "Comprovante impresso ou por SMS",
                "Receba por aproximação (NFC)",
                "Aceite Pix com QR CODE",
                "Chip 4G Grátis + Wi-Fi",
                "Tela Touch screen",
                "Sistema Android",
                "Gestão de produtos/estoque (Confira disponibilidade)",
            ],
            oldPrice: 597.0,
            newPrice: 497.0,
            installmentPrice: 41.42,
            discount: 16,
            button: "Pedir Yelly Smart",
        },
    },

    basic: {
        Mini: {
            name: "Yelly Mini",
            desc: "A mais portátil!",
            imageUrl:
                "https://yelly.com.br/wp-content/uploads/2025/05/54401cb192b8ff9be46b0a853bf4d64643764f8c.png",
            items: [
                "Frete Grátis",
                "+5% desconto  extra no PIX",
                "Link de Pagamento Grátis (Consulte condições)",
                "Comprovante impresso ou por SMS",
                "Receba por aproximação (NFC)",
                "Aceite Pix com QR CODE",
                "Chip 3g Grátis",
                "Tela Touch screen",
                "Sistema Android",
                "Gestão de produtos/estoque (Confira disponibilidade)",
            ],
            oldPrice: 337.0,
            newPrice: 99.0,
            installmentPrice: 8.25,
            discount: 70,
            button: "Pedir com desconto",
        },
        Pro: {
            name: "Yelly Pro",
            desc: "O melhor custo-benefício!",
            imageUrl:
                "https://yelly.com.br/wp-content/uploads/2025/06/PRO-DESCONTO-BASIC.png",
            items: [
                "Frete Grátis",
                "+5% desconto  extra no PIX",
                "Link de Pagamento Grátis (Consulte condições)",
                "Comprovante impresso ou por SMS",
                "Receba por aproximação (NFC)",
                "Aceite Pix com QR CODE",
                "Chip 4G Grátis + Wi-Fi",
                "Tela Touch screen",
                "Sistema Android",
                "Gestão de produtos/estoque (Confira disponibilidade)",
            ],
            oldPrice: 497.0,
            newPrice: 249.0,
            installmentPrice: 20.75,
            discount: 49,
            button: "Pedir com desconto",
        },
        Smart: {
            name: "Yelly Smart",
            desc: "A mais moderna!",
            imageUrl:
                "https://yelly.com.br/wp-content/uploads/2025/06/SMART-DESCONTO-MAX.png",
            items: [
                "Frete Grátis",
                "+5% desconto  extra no PIX",
                "Link de Pagamento Grátis (Consulte condições)",
                "Comprovante impresso ou por SMS",
                "Receba por aproximação (NFC)",
                "Aceite Pix com QR CODE",
                "Chip 4G Grátis + Wi-Fi",
                "Tela Touch screen",
                "Sistema Android",
                "Gestão de produtos/estoque (Confira disponibilidade)",
            ],
            oldPrice: 597.0,
            newPrice: 399.0,
            installmentPrice: 33.25,
            discount: 24,
            button: "Pedir com desconto",
        },
    },

    economic: {
        Plus: {
            name: "YELLY PRO PLUS",
            desc: "Máquina de cartão 100% Yelly, o nosso mais novo lançamento no mercado. Confira nossa maquininha de subadquirente. Recado importante: Nesta modalidade não será possível solicitar antecipação por demanda.",
            imageUrl:
                "https://yelly.com.br/wp-content/uploads/2025/05/f501e1a4387dd5f16cd0bd4b5938d9fb95904198.png",
            items: [
                "Frete Grátis",
                "+5% desconto  extra no PIX",
                "Link de Pagamento Grátis (Consulte condições)",
                "Comprovante impresso ou por SMS",
                "Receba por aproximação (NFC)",
                "Aceite Pix com QR CODE",
                "Tela Touch screen",
                "Chip 3G Grátis + Wi-Fi",
                "Máquina 100% Yelly",
            ],
            oldPrice: 799.0,
            newPrice: 399.0,
            installmentPrice: 33.25,
            discount: 50,
            button: "Pedir Yelly Plus",
        },
    },
};