import { MaquininhaPorPlano } from "@/types/maquinas";

export const MaquinasYelly: MaquininhaPorPlano = {

    max: {
        Mini: {
            name: "Yelly Mini",
            desc: "A mais portátil",
            imageUrl:
              "https://yelly.com.br/wp-content/uploads/2025/07/MINI-MAX.png", // novo
            items: [
              "Frete Grátis",
              "+5% desconto  extra no PIX",
              "Link de Pagamento Grátis (Consulte condições)",
              "Comprovante por SMS",
              "Receba por aproximação (NFC)",
              "Aceite Pix com QR CODE",
              "Chip 3g Grátis + Wi-Fi",
              "Tela Touch screen",
              "Sistema Android",
              "Gestão de produtos/estoque (Confira disponibilidade)",
            ],
            oldPrice: 337.0,
            newPrice: 197.00,
            installmentPrice: 16.42,
            discount: 41,
            button: "Pedir Yelly Mini",
        },
        Pro: {
            name: "Yelly Pro",
            desc: "A mais completa",
            imageUrl:
                "https://yelly.com.br/wp-content/uploads/2025/07/PRO-MAX.png",
            items: [
                "Frete Grátis",
                "+5% desconto  extra no PIX",
                "Link de Pagamento Grátis (Consulte condições)",
                "Comprovante impresso ou por SMS",
                "Receba por aproximação (NFC)",
                "Aceite Pix com QR CODE",
                "Chip 4G Grátis + Wi-Fi",
                "Tela Touch screen",
                "Sistema Android",
                "Gestão de produtos/estoque (Confira disponibilidade)",
            ],
            oldPrice: 497.0,
            newPrice: 297.0,
            installmentPrice: 24.75,
            discount: 40,
            button: "Pedir Yelly Pro",
        },
        Smart: {
            name: "Yelly Smart",
            desc: "A mais moderna",
            imageUrl:
              "https://yelly.com.br/wp-content/uploads/2025/07/SMART-MAX.png",
            items: [
              "Frete Grátis",
              "+5% desconto  extra no PIX",
              "Link de Pagamento Grátis (Consulte condições)",
              "Comprovante impresso ou por SMS",
              "Receba por aproximação (NFC)",
              "Aceite Pix com QR CODE",
              "Chip 4G Grátis + Wi-Fi",
              "Tela Touch screen",
              "Sistema Android",
              "Gestão de produtos/estoque (Confira disponibilidade)",
            ],
            oldPrice: 597.0,
            newPrice: 497.0,
            installmentPrice: 41.42,
            discount: 16,
            button: "Pedir Yelly Smart",
          },
    },

    basic: {
        Minizinha: {
            name: "Yelly Minizinha",
            desc: "Super novidade",
            imageUrl:
              "https://yelly.com.br/wp-content/uploads/2025/07/MINIZINHA-BASIC.png",
            items: [
              "Frete Grátis",
              "+5% desconto  extra no PIX",
              "Link de Pagamento Grátis (Consulte condições)",
              "Comprovante por SMS",
              "Receba por aproximação (NFC)",
              "Aceite Pix com QR CODE",
              "Precisa de celular",
              "Tela Touch screen",
              "Sistema Android",
              "Gestão de produtos/estoque (Confira disponibilidade)",
            ],
            oldPrice: 97.0,
            newPrice: 29.0,
            installmentPrice: 2.49,
            discount: 70,
            button: "Pedir com desconto",
        },
        Mini: {
            name: "Yelly Mini",
            desc: "A mais portátil",
            imageUrl:
              "https://yelly.com.br/wp-content/uploads/2025/07/MINI-BASIC.png",
            items: [
              "Frete Grátis",
              "+5% desconto  extra no PIX",
              "Link de Pagamento Grátis (Consulte condições)",
              "Comprovante impresso ou por SMS",
              "Receba por aproximação (NFC)",
              "Aceite Pix com QR CODE",
              "Chip 3g Grátis",
              "Tela Touch screen",
              "Sistema Android",
              "Gestão de produtos/estoque (Confira disponibilidade)",
            ],
            oldPrice: 337.0,
            newPrice: 99.0,
            installmentPrice: 8.25,
            discount: 70,
            button: "Pedir com desconto",
        },
        Pro: {
            name: "Yelly Pro",
            desc: "A mais completa",
            imageUrl:
              "https://yelly.com.br/wp-content/uploads/2025/07/PRO-BASIC.png",
            items: [
              "Frete Grátis",
              "+5% desconto  extra no PIX",
              "Link de Pagamento Grátis (Consulte condições)",
              "Comprovante impresso ou por SMS",
              "Receba por aproximação (NFC)",
              "Aceite Pix com QR CODE",
              "Chip 4G Grátis + Wi-Fi",
              "Tela Touch screen",
              "Sistema Android",
              "Gestão de produtos/estoque (Confira disponibilidade)",
            ],
            oldPrice: 497.0,
            newPrice: 249.0,
            installmentPrice: 20.75,
            discount: 49,
            button: "Pedir com desconto",
        },
        
    },

    economic: {
        Plus: {
            name: "YELLY PRO PLUS",
            desc: "Máquina 100% Yelly",
            imageUrl:
              "https://yelly.com.br/wp-content/uploads/2025/07/PLUS-ECONOMIC.png",
            items: [
              "Frete Grátis",
              "+5% desconto  extra no PIX",
              "Link de Pagamento Grátis (Consulte condições)",
              "Comprovante impresso ou por SMS",
              "Receba por aproximação (NFC)",
              "Aceite Pix com QR CODE",
              "Tela Touch screen",
              "Chip 4G Grátis + Wi-Fi",
              "Máquina 100% Yelly",
            ],
            oldPrice: 799.0,
            newPrice: 399.0,
            installmentPrice: 33.25,
            discount: 50,
            button: "Pedir Yelly Plus",
        },
    },
};